app.env: local

logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app
    username: root
    password: password
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
